# Generated by Django 5.1.2 on 2024-10-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbeiro', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
